### 작성자: AISchool (http://aischool.ai/), Daniel Park

# 2장. 쉽게 사용하는 데이터 분석 공구세트 Pandas, Numpy
#### 엑셀은 이제 안녕. Python으로 진정한 데이터 사이언티스트로 거듭나자  
- 엑셀과 같은 행과 열을 가진 Table 데이터를 다루는 패키지, Numpy와 Pandas  
- Numpy와 Pandas를 이용하여 데이터를 나누고, 필터링하고, 정렬해보자  
- 원티드 실제 DB의 데이터를 살펴보자! 국민연금 사업장 데이터로 배우는 데이터 분석의 첫 단추, EDA  
- 1912년 타이타닉 사고의 데이터를 살펴보자!  

**(학습 내용: Numpy, Pandas, Series, DataFrame, Indexing, csv 읽고 쓰기, merge, Kaggle, EDA(Exploratory Data Analysis), plot)**

## 2.1. 쉽게 사용하는 데이터 분석 공구세트 (PPT 진행)

## 2.2 도구들의 기초 개념 잡기

### Numpy

#### numpy 기본 1. 다차원 배열 만들기

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([[1,2,3,4],[11,12,13,14]])

In [4]:
arr2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [9]:
r4 = np.random.randn(2,2,5,5).round(3)
r4

array([[[[ 0.657,  1.479, -0.791, -0.228,  0.533],
         [ 1.145,  0.152,  0.3  ,  0.693, -1.412],
         [ 0.996,  0.102, -1.054, -0.655,  0.676],
         [-0.863, -2.062, -0.733,  1.764, -0.612],
         [ 0.731,  0.705,  0.241, -1.006, -0.528]],

        [[-0.177,  0.698,  1.081,  0.661,  0.675],
         [-0.78 , -0.219,  0.038,  3.08 ,  0.191],
         [ 0.626,  1.042, -1.343,  0.992,  1.174],
         [-1.262, -0.766,  0.792,  0.688, -0.231],
         [ 0.923,  1.599, -2.386, -0.808, -0.479]]],


       [[[-1.335, -0.518, -1.48 ,  1.581,  1.248],
         [ 1.726, -0.646, -2.166,  0.394,  1.045],
         [ 1.614, -0.144, -1.814,  1.787,  0.54 ],
         [ 1.355,  2.004,  0.191,  2.406,  0.855],
         [-0.561, -0.114,  2.229,  0.793,  0.422]],

        [[ 1.603,  0.992,  1.098,  0.012, -1.494],
         [-0.142,  0.418,  1.203, -1.975,  1.694],
         [ 0.673,  1.364, -1.035, -1.352,  0.293],
         [ 0.021,  0.118, -0.383,  0.762, -0.593],
         [ 0.517, -0.51

##### <연습문제 2-1>
1  3  5  7  9  
2  4  6  8  10  
  
형태의 2x5 행렬을 만들어 보세요

In [6]:
arr = np.array([[1,3,5,7,9],[2,4,6,8,10]])
arr

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [7]:
arr.shape

(2, 5)

#### numpy 기본 2. Indexing과 Slicing

In [10]:
r4[1][0]

array([[-1.335, -0.518, -1.48 ,  1.581,  1.248],
       [ 1.726, -0.646, -2.166,  0.394,  1.045],
       [ 1.614, -0.144, -1.814,  1.787,  0.54 ],
       [ 1.355,  2.004,  0.191,  2.406,  0.855],
       [-0.561, -0.114,  2.229,  0.793,  0.422]])

In [11]:
r4[1][0][2]

array([ 1.614, -0.144, -1.814,  1.787,  0.54 ])

In [12]:
r4[1,0,2]

array([ 1.614, -0.144, -1.814,  1.787,  0.54 ])

In [13]:
r4[1,0,2][0:4:2]

array([ 1.614, -1.814])

In [14]:
r4[1][0][1:4:2]

array([[ 1.726, -0.646, -2.166,  0.394,  1.045],
       [ 1.355,  2.004,  0.191,  2.406,  0.855]])

In [17]:
r4[1,0][1:4:2][1][3:]

array([2.406, 0.855])

#### numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [19]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [20]:
arr + arr

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [21]:
arr + 20

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [22]:
arr * 100

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [23]:
arr.prod()

411840

In [24]:
arr.sum(axis=0)

array([11, 13, 15, 17])

In [25]:
arr.sum(axis=1)

array([10, 46])

#### numpy 기본 4. 고급 Broadcasting

In [26]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [27]:
arr1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [28]:
arr2

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [30]:
arr1 + arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [31]:
arr1 + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [32]:
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Pandas

#### pandas 기본 1. 『 Series 』 행×값 데이터 

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 아래 블럭은 그냥 실행해주세요!! 주가 데이터를 불러오고, series 하나를 추출합니다..

In [ ]:
# 이 블럭은 그냥 실행해주세요!! 주가 데이터를 불러오고, series 하나를 고릅니다.

주가_데이터 = pd.read_csv('stock.adj_close.csv', index_col=0)
my_series = 주가_데이터.loc['A005930']['2020-09-09':]

#### pandas 기본 2. 『 Series 』   접근, 연산, 생성

#### pandas 기본 3. 『 DataFrame 』 행×열 데이터 

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 아래 블럭은 그냥 실행해주세요!! 불러온 주가 데이터에서 불러오고, dataframe 하나를 추출합니다..

In [ ]:
my_df = 주가_데이터.T.loc['2020-09-09':,'A005900':'A006000']

#### pandas 기본 4. 『 DataFrame 』  접근

##### <연습문제 2-2>
my_df에서 A005950 종목의  2020-09-16의 주가를 뽑아보세요

##### <연습문제 2-3>
my_df에서 A005950 종목의  2020-09-10 ~ 2020-09-15 의 주가를 뽑아보세요

##### <연습문제 2-4>
my_df에서 A005930과 A005950 종목의  2020-09-10 ~ 2020-09-17 의 주가를 **이틀 간격**으로 뽑아보세요

#### pandas 기본 5. 『 DataFrame 』  접근 2,  연산

##### <연습문제 2-5>
my_df에서 A005950종목의 전체 기간의 주가의 평균을 구해보시오

##### <연습문제 2-6>
my_df에서 A005980종목 2020-09-14 이후 주가의 일별 상한가를 구해보세요 (상한가: 30% 상승)

##### <연습문제 2-7>
my_df에서 모든 종목의 2020-09-17 ~ 2020-09-24 기간의 수익률을 구해보세요 (% 단위)

#### pandas 기본 6. 『 DataFrame 』  연산 2,  정렬

##### <연습문제 2-8>
my_df에서 2020-09-16일자의 주가 들을 내림차순 순서로 정렬해보세요

##### <연습문제 2-9>
my_df에서 2020-09-09 ~ 2020-09-18 의 전 종목 수익률을 계산하여 순위를 출력해보세요 (수익률 높은 순)

##### 총 정리에 있는 다른 많은 연산들도 한번 코딩해보세요!

#### pandas 기본 7. 『 DataFrame 』  만들기,  행 열 추가하기

##### 새로운 열 추가

##### 새로운 행 추가

##### <연습문제 2-10>
trafic_data에  '중고나라' 열 데이터를 추가하고, 50000으로 값을 지정해주세요

##### <연습문제 2-11>
trafic_data의  '중고나라', 10/24, 10/25 트래픽을 75000의 값을 지정해주세요

#### matplotlib으로 그래프 그리기

##### <연습문제 2-12>
trafic_data에서  '중고나라'의 일자별 Bar 그래프를 그려보세요

#### seaborn 으로 데이터 분포 살펴보기

##### <연습문제 2-13>
성별 별로, 팁을 준 횟수를 차트로 그려보세요

## 2.3. 공구세트로 데이터 분석을 시작해보자!

#### 데이터 파일 불러오기, csv파일로 저장하기