### 작성자: AISchool (http://aischool.ai/), Daniel Park

# 2장. 쉽게 사용하는 데이터 분석 공구세트 Pandas, Numpy
#### 엑셀은 이제 안녕. Python으로 진정한 데이터 사이언티스트로 거듭나자  
- 엑셀과 같은 행과 열을 가진 Table 데이터를 다루는 패키지, Numpy와 Pandas  
- Numpy와 Pandas를 이용하여 데이터를 나누고, 필터링하고, 정렬해보자  
- 원티드 실제 DB의 데이터를 살펴보자! 국민연금 사업장 데이터로 배우는 데이터 분석의 첫 단추, EDA  
- 1912년 타이타닉 사고의 데이터를 살펴보자!  

**(학습 내용: Numpy, Pandas, Series, DataFrame, Indexing, csv 읽고 쓰기, merge, Kaggle, EDA(Exploratory Data Analysis), plot)**

## 2.1. 쉽게 사용하는 데이터 분석 공구세트 (PPT 진행)

## 2.2 도구들의 기초 개념 잡기

### Numpy

#### numpy 기본 1. 다차원 배열 만들기

In [8]:
# numpy 임포트
import numpy as np

In [9]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [10]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [11]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [12]:
# 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [13]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3)   # 랜덤한 숫자 배열 만들기

In [14]:
z1, o2, r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[ 0.0402547 , -0.08507593,  0.88660565],
        [-0.43065279,  0.82563845,  0.01431215]]))

In [15]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [16]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 0.589,  1.187,  0.176, -0.246,  0.179],
         [-0.478, -1.146,  0.724, -0.151, -1.601],
         [-1.308, -0.734,  0.776,  0.085, -0.976],
         [ 1.311, -1.668, -1.122, -1.09 , -0.358]],

        [[ 0.205, -0.76 , -0.236,  0.394,  0.385],
         [-0.959, -1.043,  0.841,  0.186, -0.595],
         [-1.17 ,  1.007, -2.02 ,  1.205, -1.255],
         [ 0.98 ,  0.82 ,  0.323, -1.686, -0.325]]],


       [[[ 0.449, -2.085, -0.414,  0.26 , -1.198],
         [-0.208, -0.718,  0.467,  0.644,  0.682],
         [ 0.954,  0.513,  2.057, -1.403,  0.909],
         [ 0.202,  0.201,  0.408,  2.635,  1.096]],

        [[ 0.777, -1.045,  0.14 , -0.15 , -0.706],
         [-0.166, -0.311, -0.793,  0.008,  0.838],
         [-1.946,  0.251,  0.059, -0.074, -0.291],
         [-0.777,  0.252,  1.034, -0.391, -1.324]]]])

##### <연습문제 2-1>
1  3  5  7  9  
2  4  6  8  10  
  
형태의 2x5 행렬을 만들어 보세요

In [17]:
np.array([[1,3,5,7,9],[2,4,6,8,10]])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

#### numpy 기본 2. Indexing과 Slicing

In [18]:
r4

array([[[[ 0.589,  1.187,  0.176, -0.246,  0.179],
         [-0.478, -1.146,  0.724, -0.151, -1.601],
         [-1.308, -0.734,  0.776,  0.085, -0.976],
         [ 1.311, -1.668, -1.122, -1.09 , -0.358]],

        [[ 0.205, -0.76 , -0.236,  0.394,  0.385],
         [-0.959, -1.043,  0.841,  0.186, -0.595],
         [-1.17 ,  1.007, -2.02 ,  1.205, -1.255],
         [ 0.98 ,  0.82 ,  0.323, -1.686, -0.325]]],


       [[[ 0.449, -2.085, -0.414,  0.26 , -1.198],
         [-0.208, -0.718,  0.467,  0.644,  0.682],
         [ 0.954,  0.513,  2.057, -1.403,  0.909],
         [ 0.202,  0.201,  0.408,  2.635,  1.096]],

        [[ 0.777, -1.045,  0.14 , -0.15 , -0.706],
         [-0.166, -0.311, -0.793,  0.008,  0.838],
         [-1.946,  0.251,  0.059, -0.074, -0.291],
         [-0.777,  0.252,  1.034, -0.391, -1.324]]]])

In [21]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[ 0.449, -2.085, -0.414,  0.26 , -1.198],
       [-0.208, -0.718,  0.467,  0.644,  0.682],
       [ 0.954,  0.513,  2.057, -1.403,  0.909],
       [ 0.202,  0.201,  0.408,  2.635,  1.096]])

In [22]:
r4[1][0][2]

array([ 0.954,  0.513,  2.057, -1.403,  0.909])

In [23]:
r4[1][0][2][4]

0.909

In [24]:
r4[1][0][2][0:4:2]

array([0.954, 2.057])

In [27]:
r4

array([[[[ 0.589,  1.187,  0.176, -0.246,  0.179],
         [-0.478, -1.146,  0.724, -0.151, -1.601],
         [-1.308, -0.734,  0.776,  0.085, -0.976],
         [ 1.311, -1.668, -1.122, -1.09 , -0.358]],

        [[ 0.205, -0.76 , -0.236,  0.394,  0.385],
         [-0.959, -1.043,  0.841,  0.186, -0.595],
         [-1.17 ,  1.007, -2.02 ,  1.205, -1.255],
         [ 0.98 ,  0.82 ,  0.323, -1.686, -0.325]]],


       [[[ 0.449, -2.085, -0.414,  0.26 , -1.198],
         [-0.208, -0.718,  0.467,  0.644,  0.682],
         [ 0.954,  0.513,  2.057, -1.403,  0.909],
         [ 0.202,  0.201,  0.408,  2.635,  1.096]],

        [[ 0.777, -1.045,  0.14 , -0.15 , -0.706],
         [-0.166, -0.311, -0.793,  0.008,  0.838],
         [-1.946,  0.251,  0.059, -0.074, -0.291],
         [-0.777,  0.252,  1.034, -0.391, -1.324]]]])

In [28]:
r4[1][0][1:4:2]

array([[-0.208, -0.718,  0.467,  0.644,  0.682],
       [ 0.202,  0.201,  0.408,  2.635,  1.096]])

In [45]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([2.635, 1.096])

In [30]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([2.635, 1.096])

#### numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [46]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [47]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [48]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [49]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [50]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [52]:
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [51]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [37]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [38]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

#### numpy 기본 4. 고급 Broadcasting

In [39]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [40]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [41]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [42]:
#  (4x1) + (1x3)
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Pandas

#### pandas 기본 1. 『 Series 』 행×값 데이터 

In [54]:
#pandas 임포트
import pandas as pd
my_series = pd.read_csv("/Users/ijuyeong/Downloads/project/stock.adj_close.csv")
my_series

Symbol  2018-06-01  2018-06-04  2018-06-05  2018-06-07  2018-06-08  \
0     A000020     11550.0     11750.0     11700.0     11650.0     11500.0   
1     A000030     15500.0     15950.0     16050.0     16500.0     16600.0   
2     A000040      2992.0      3021.0      3025.0      3069.0      3045.0   
3     A000050     13200.0     13550.0     13600.0     13800.0     13800.0   
4     A000060     20050.0     20050.0     20150.0     20050.0     20400.0   
...       ...         ...         ...         ...         ...         ...   
2269  A950160     38600.0     36400.0     36350.0     38700.0     40200.0   
2270  A950170     13850.0     14250.0     14450.0     14300.0     14150.0   
2271  A950180         NaN         NaN         NaN         NaN         NaN   
2272  A950190         NaN         NaN         NaN         NaN         NaN   
2273  A950200         NaN         NaN         NaN         NaN         NaN   

      2018-06-11  2018-06-12  2018-06-14  2018-06-15  ...  2020-09-07  \
0        11500.0     11650.0     12000.0     11800.0  ...     25550.0   
1        16650.0     16850.0     16500.0     16100.0  ...     14800.0   
2         2984.0      2976.0      3033.0      3033.0  ...       980.0   
3        13800.0     13650.0     13850.0     14500.0  ...     11100.0   
4        20150.0     20700.0     20950.0     20150.0  ...     12700.0   
...          ...         ...         ...         ...  ...         ...   
2269     39250.0     38300.0     38350.0     39000.0  ...      9540.0   
2270     13650.0     14050.0     13600.0     13550.0  ...      4040.0   
2271         NaN         NaN         NaN         NaN  ...     13200.0   
2272         NaN         NaN         NaN         NaN  ...     32200.0   
2273         NaN         NaN         NaN         NaN  ...     16750.0   

      2020-09-08  2020-09-09  2020-09-10  2020-09-11  2020-09-14  2020-09-15  \
0        23650.0     24550.0     25950.0     26750.0     26300.0     25400.0   
1        14800.0     14800.0     14800.0     14800.0     14800.0     14800.0   
2          932.0       741.0       875.0       840.0       860.0       833.0   
3        11350.0     11550.0     11500.0     11550.0     11300.0     11300.0   
4        12700.0     12650.0     12700.0     12800.0     13000.0     13200.0   
...          ...         ...         ...         ...         ...         ...   
2269      9540.0      9540.0      9540.0      9540.0      9540.0      9540.0   
2270      4050.0      4245.0      4275.0      4200.0      4195.0      4070.0   
2271     13150.0     13100.0     13150.0     13100.0     13900.0     13250.0   
2272     31200.0     30400.0     30500.0     30150.0     30050.0     31450.0   
2273     16950.0     17250.0     17100.0     17350.0     17450.0     15800.0   

      2020-09-16  2020-09-17  2020-09-18  
0        25050.0     25300.0     25050.0  
1        14800.0     14800.0     14800.0  
2          817.0       812.0       796.0  
3        11050.0     10900.0     10750.0  
4        13150.0     13150.0     13200.0  
...          ...         ...         ...  
2269      9540.0      8010.0      8010.0  
2270      4045.0      4015.0      4055.0  
2271     13350.0     13550.0     13450.0  
2272     31750.0     31200.0     30350.0  
2273     15100.0     14700.0     14550.0  

[2274 rows x 569 columns]

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 아래 블럭은 그냥 실행해주세요!! 주가 데이터를 불러오고, series 하나를 추출합니다..

#### pandas 기본 2. 『 Series 』   접근, 연산, 생성

In [59]:
my_series['2020-09-15'] 

0       25400.0
1       14800.0
2         833.0
3       11300.0
4       13200.0
         ...   
2269     9540.0
2270     4070.0
2271    13250.0
2272    31450.0
2273    15800.0
Name: 2020-09-15, Length: 2274, dtype: float64

In [58]:
my_series.loc['2020-09-15']   # 인덱스로 접근

KeyError: '2020-09-15'

In [56]:
my_series.iloc[4]    # 배열 번호로 접근

Symbol        A000060
2018-06-01    20050.0
2018-06-04    20050.0
2018-06-05    20150.0
2018-06-07    20050.0
               ...   
2020-09-14    13000.0
2020-09-15    13200.0
2020-09-16    13150.0
2020-09-17    13150.0
2020-09-18    13200.0
Name: 4, Length: 569, dtype: object

In [60]:
my_series.loc['2020-09-15':'2020-09-17']  # 인덱스로 Slicing

Empty DataFrame
Columns: [Symbol, 2018-06-01, 2018-06-04, 2018-06-05, 2018-06-07, 2018-06-08, 2018-06-11, 2018-06-12, 2018-06-14, 2018-06-15, 2018-06-18, 2018-06-19, 2018-06-20, 2018-06-21, 2018-06-22, 2018-06-25, 2018-06-26, 2018-06-27, 2018-06-28, 2018-06-29, 2018-07-02, 2018-07-03, 2018-07-04, 2018-07-05, 2018-07-06, 2018-07-09, 2018-07-10, 2018-07-11, 2018-07-12, 2018-07-13, 2018-07-16, 2018-07-17, 2018-07-18, 2018-07-19, 2018-07-20, 2018-07-23, 2018-07-24, 2018-07-25, 2018-07-26, 2018-07-27, 2018-07-30, 2018-07-31, 2018-08-01, 2018-08-02, 2018-08-03, 2018-08-06, 2018-08-07, 2018-08-08, 2018-08-09, 2018-08-10, 2018-08-13, 2018-08-14, 2018-08-16, 2018-08-17, 2018-08-20, 2018-08-21, 2018-08-22, 2018-08-23, 2018-08-24, 2018-08-27, 2018-08-28, 2018-08-29, 2018-08-30, 2018-08-31, 2018-09-03, 2018-09-04, 2018-09-05, 2018-09-06, 2018-09-07, 2018-09-10, 2018-09-11, 2018-09-12, 2018-09-13, 2018-09-14, 2018-09-17, 2018-09-18, 2018-09-19, 2018-09-20, 2018-09-21, 2018-09-27, 2018-09-28, 2018-10-01, 2018-10-02, 2018-10-04, 2018-10-05, 2018-10-08, 2018-10-10, 2018-10-11, 2018-10-12, 2018-10-15, 2018-10-16, 2018-10-17, 2018-10-18, 2018-10-19, 2018-10-22, 2018-10-23, 2018-10-24, 2018-10-25, 2018-10-26, 2018-10-29, ...]
Index: []

[0 rows x 569 columns]

my_series.iloc[4:7]    # 배열 번호로 Slicing (끝 포함 X)

In [62]:
my_series.iloc[4:] + my_series.iloc[4:]

Symbol  2018-06-01  2018-06-04  2018-06-05  2018-06-07  \
4     A000060A000060     40100.0     40100.0     40300.0     40100.0   
5     A000070A000070    240000.0    246000.0    247000.0    249000.0   
6     A000080A000080     40400.0     40800.0     40700.0     42000.0   
7     A000100A000100     89958.0     85378.0     82812.0     82996.0   
8     A000120A000120    296000.0    306000.0    305000.0    308000.0   
...              ...         ...         ...         ...         ...   
2269  A950160A950160     77200.0     72800.0     72700.0     77400.0   
2270  A950170A950170     27700.0     28500.0     28900.0     28600.0   
2271  A950180A950180         NaN         NaN         NaN         NaN   
2272  A950190A950190         NaN         NaN         NaN         NaN   
2273  A950200A950200         NaN         NaN         NaN         NaN   

      2018-06-08  2018-06-11  2018-06-12  2018-06-14  2018-06-15  ...  \
4        40800.0     40300.0     41400.0     41900.0     40300.0  ...   
5       247000.0    250000.0    243000.0    236000.0    242000.0  ...   
6        41500.0     41700.0     41400.0     41300.0     41200.0  ...   
7        83912.0     84278.0     84828.0     83546.0     83180.0  ...   
8       308000.0    323000.0    323000.0    313000.0    304000.0  ...   
...          ...         ...         ...         ...         ...  ...   
2269     80400.0     78500.0     76600.0     76700.0     78000.0  ...   
2270     28300.0     27300.0     28100.0     27200.0     27100.0  ...   
2271         NaN         NaN         NaN         NaN         NaN  ...   
2272         NaN         NaN         NaN         NaN         NaN  ...   
2273         NaN         NaN         NaN         NaN         NaN  ...   

      2020-09-07  2020-09-08  2020-09-09  2020-09-10  2020-09-11  2020-09-14  \
4        25400.0     25400.0     25300.0     25400.0     25600.0     26000.0   
5       134400.0    136000.0    133000.0    132600.0    130800.0    135000.0   
6        73400.0     76100.0     74100.0     75200.0     74700.0     74600.0   
7       130400.0    131000.0    128000.0    129000.0    133200.0    131400.0   
8       320000.0    312000.0    316000.0    312000.0    313000.0    316000.0   
...          ...         ...         ...         ...         ...         ...   
2269     19080.0     19080.0     19080.0     19080.0     19080.0     19080.0   
2270      8080.0      8100.0      8490.0      8550.0      8400.0      8390.0   
2271     26400.0     26300.0     26200.0     26300.0     26200.0     27800.0   
2272     64400.0     62400.0     60800.0     61000.0     60300.0     60100.0   
2273     33500.0     33900.0     34500.0     34200.0     34700.0     34900.0   

      2020-09-15  2020-09-16  2020-09-17  2020-09-18  
4        26400.0     26300.0     26300.0     26400.0  
5       132400.0    130800.0    129000.0    128800.0  
6        77000.0     75900.0     74300.0     73700.0  
7       137400.0    136800.0    132800.0    133200.0  
8       325000.0    355000.0    359000.0    364000.0  
...          ...         ...         ...         ...  
2269     19080.0     19080.0     16020.0     16020.0  
2270      8140.0      8090.0      8030.0      8110.0  
2271     26500.0     26700.0     27100.0     26900.0  
2272     62900.0     63500.0     62400.0     60700.0  
2273     31600.0     30200.0     29400.0     29100.0  

[2270 rows x 569 columns]

In [63]:
my_series.loc['2020-09-15'::2] + 30000  # Scalar Broadcasting

TypeError: can only concatenate str (not "int") to str

In [ ]:
my_series.iloc[4:].mean()    # 평균 aggregation

NameError: name 'my_series' is not defined

In [ ]:
new_sr = pd.Series([11,22,3,45], name='apple',
                   index=['a','b','xs','e11'])
new_sr

#### pandas 기본 3. 『 DataFrame 』 행×열 데이터 

##### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 아래 블럭은 그냥 실행해주세요!! 불러온 주가 데이터에서 불러오고, dataframe 하나를 추출합니다..

In [ ]:
my_df = 주가_데이터.T.loc['2020-09-09':,'A005900':'A006000']

In [ ]:
my_df

#### pandas 기본 4. 『 DataFrame 』  접근

my_df.loc['2020-09-15', 'A005930']   # .loc 단일 원소 접근

In [ ]:
# .loc [ 인덱스, 컬럼 slice ] 로 접근  →  Series 반환
my_df.loc['2020-09-15', 'A005930':'A005950']

In [ ]:
# .loc [ 인덱스 slice, 컬럼이름 ] 으로 접근  →  Series 반환
my_df.loc['2020-09-15':'2020-09-18', 'A005930']

In [ ]:
#  .loc [ index slice, column slice ]  →  DataFrame 반환
my_df.loc['2020-09-14':'2020-09-18':2, 'A005940':'A005980']

In [ ]:
# .iloc [ index, column slice ]  으로 접근  →  Series 반환
my_df.iloc[0, 3:]  

In [ ]:
#  .iloc [ index slice, column slice ]  →  DataFrame 반환
my_df.iloc[4:7:2, 1:4]

##### <연습문제 2-2>
my_df에서 A005950 종목의  2020-09-16의 주가를 뽑아보세요

##### <연습문제 2-3>
my_df에서 A005950 종목의  2020-09-10 ~ 2020-09-15 의 주가를 뽑아보세요

##### <연습문제 2-4>
my_df에서 A005930과 A005950 종목의  2020-09-10 ~ 2020-09-17 의 주가를 **이틀 간격**으로 뽑아보세요

#### pandas 기본 5. 『 DataFrame 』  접근 2,  연산

In [ ]:
# ::으로 모든 원소 지칭
my_df.loc[::, 'A005930']

In [ ]:
# : 한번만 사용 가능
my_df.iloc[5, :]

In [ ]:
# shape 보기
my_df.iloc[5, :].shape

In [ ]:
my_df.iloc[5:, ::3]

In [ ]:
my_df.iloc[5:, ::3].shape

In [ ]:
my_df.iloc[::4].loc[:, 'A005950':]

In [ ]:
my_df.loc['2020-09-09'::4].iloc[:,2:]

In [ ]:
my_df_2 = my_df.loc[:'2020-09-11','A005960':]

In [ ]:
my_df_2

In [ ]:
my_df_2 * 1.30   # Broadcasting

In [ ]:
my_df_2.mean(axis=0)  # 평균 Agg

##### <연습문제 2-5>
my_df에서 A005950종목의 전체 기간의 주가의 평균을 구해보시오

##### <연습문제 2-6>
my_df에서 A005980종목 2020-09-14 이후 주가의 일별 상한가를 구해보세요 (상한가: 30% 상승)

##### <연습문제 2-7>
my_df에서 모든 종목의 2020-09-17 ~ 2020-09-24 기간의 수익률을 구해보세요 (% 단위)

#### pandas 기본 6. 『 DataFrame 』  연산 2,  정렬

#### pandas 기본 7. 『 DataFrame 』  만들기,  행 열 추가하기

In [ ]:
# 데이터 인덱스, 컬럼으로 DataFrame 생성하기
pd.DataFrame([[0,1,2],[3,4,5]], 
             index=['00','11'],
             columns=['a','b','c'])

In [ ]:
# 넘파이 배열로 DataFrame 생성하기
pd.DataFrame(np.ones((3,5)))

In [ ]:
trafic_data = pd.DataFrame(
    [[9800,5500],[10200,6600]],
    index=['10/22','10/23'],
    columns=['원티드','사람인'])
trafic_data   # trafic_data 라는 DataFrame 생성

##### 새로운 열 추가

In [ ]:
# 새로운 '잡플래닛' 열 (빈 데이터) 추가하기
trafic_data.loc[:,'잡플래닛'] = np.nan
trafic_data

In [ ]:
# 새로운 '잡코리아' 열 데이터 추가하기
trafic_data.loc[:,'잡코리아'] = [980, 1020]
trafic_data

In [ ]:
# 숫자를 하나만 주면 broadcast 된다.
trafic_data.loc[:,'스펙업'] = 20000
trafic_data

##### 새로운 행 추가

In [ ]:
# 새로운 10/24 행 데이터추가하기
trafic_data.loc['10/24'] = [12500,4520,3000,
                           780, 21000]
trafic_data

In [ ]:
# 값을 하나만 지정하면, broadcast 된다
trafic_data.loc['10/25'] = 2000
trafic_data

In [ ]:
trafic_data.loc['10/22', '잡플래닛'] = 99
trafic_data

##### <연습문제 2-10>
trafic_data에  '중고나라' 열 데이터를 추가하고, 50000으로 값을 지정해주세요

##### <연습문제 2-11>
trafic_data의  '중고나라', 10/24, 10/25 트래픽을 75000의 값을 지정해주세요

#### matplotlib으로 그래프 그리기

In [ ]:
# matplotlib 임포트,  주피터 출력설정,  한글 글꼴 지정
import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams['font.family'] = 'Malgun Gothic'  # (Windows 용) 한글 출력을 위한 글꼴 설정
#plt.rcParams['font.family'] = 'AppleGothic'  # (MAC, 리눅스 용)

In [ ]:
my_df.loc[:,'A005930'].plot();  # Series 그래프

In [ ]:
my_df.plot(grid=True);  # DataFrame 그래프

In [ ]:
my_df_2.plot(kind='bar', title='주가 흐름');

In [ ]:
trafic_data.plot(kind='scatter', grid=True,
                 x='원티드', y='사람인');

In [ ]:
trafic_data.plot(subplots=True);

##### <연습문제 2-12>
trafic_data에서  '중고나라'의 일자별 Bar 그래프를 그려보세요

#### seaborn 으로 데이터 분포 살펴보기

In [ ]:
# seaborn 임포트,  한글 글꼴 지정
import seaborn as sns
sns.set()
plt.rc('font', family='Malgun Gothic')

In [ ]:
tips = sns.load_dataset('tips')  # 내장 데이터 셋 불러오기

In [ ]:
tips.head()    # dataframe의 앞부분만 살펴보기

In [ ]:
sns.countplot(data=tips, x='day');
plt.title('요일별 팁을 준 횟수');

In [ ]:
sns.boxplot(data=tips, x='day', y='tip');
plt.title('요일별 팁의 Box Plot');

In [ ]:
sns.scatterplot(data=tips, x='total_bill', y='tip');
plt.title('식사 금액과 팁의 관계');

In [ ]:
sns.jointplot(data=tips, x="total_bill", y="tip");
plt.suptitle("식사 금액과 팁의 관계 Joint Plot", y=1.02);

In [ ]:
sns.boxplot(data=tips, x='day', y='tip');
plt.title('요일별 팁의 Box Plot');

In [ ]:
sns.violinplot(data=tips, x="day", y="tip", hue="sex")
plt.title("요일 별, 성별 팁의 Violin Plot")
plt.show()

In [ ]:
sns.distplot(tips.tip, kde=True, rug=True);
plt.title('팁의 분포');

##### <연습문제 2-13>
성별 별로, 팁을 준 횟수를 차트로 그려보세요

## 2.3. 공구세트로 데이터 분석을 시작해보자!

#### 데이터 파일 불러오기, csv파일로 저장하기

In [ ]:
# dataframe을 csv 파일로 저장
my_df_2.to_csv('my_df_2.csv')

# 한글이 포함된 경우, 엑셀을 위해 인코딩 지정
my_df_2.to_csv('my_df_2.csv', encoding='cp949')

In [ ]:
# csv 파일을 dataframe으로 불러오기
readed_df = pd.read_csv('my_df_2.csv')

# encoding 지정하여 한글이 포함된 csv 파일 불러오기
readed_df = pd.read_csv('my_df_2.csv', encoding='cp949',
                       index_col=0)
readed_df

In [ ]:
readed_df